In [1]:
import numpy as np

In [4]:
tinggi = [1.7, 1.8, 1.9, 1.10, 1.11, 1.12]
berat = [60.5, 61.5, 62.5, 63.5, 64.5, 65.5]

np_tinggi = np.array(tinggi)
np_berat = np.array(berat)
print(np_tinggi/np_berat)

np.arange(5)

[0.02809917 0.02926829 0.0304     0.01732283 0.0172093  0.01709924]


array([0, 1, 2, 3, 4])

In [5]:
arr = np.array([1,2,3,4])
arr_new = np.append(arr, [0,9,8])
arr_new

array([1, 2, 3, 4, 0, 9, 8])

In [6]:
np.delete(arr_new, 4)

array([1, 2, 3, 4, 9, 8])

# 0D / Skalar

In [9]:
arr_a = np.array(5)
print(arr_a)


5


In [10]:
arr_a.ndim

0

In [11]:
arr_a.shape

()

# 1D / Vektor

In [12]:
arr_b = np.array([1,2,3,4])
print(arr_b)

[1 2 3 4]


In [13]:
arr_b.ndim

1

In [14]:
arr_b.shape

(4,)

# 2D / Matrix

In [19]:
arr_c = np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(arr_c)

[[1 2 3 4 5]
 [5 6 7 8 9]]


In [20]:
arr_c.ndim

2

In [21]:
arr_c.shape

(2, 5)

In [22]:
arr_c.size

10

In [23]:
arr = np.arange(6)

matrix = arr.reshape(3,2)
print(matrix)

[[0 1]
 [2 3]
 [4 5]]


In [24]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [26]:
a.shape

(5,)

In [25]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 5)
[[1 2 3 4 5]]


In [31]:
a3 = a[:,np.newaxis]
print(a3)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [34]:
ae = np.expand_dims(a,axis=1)
ae.shape


(5, 1)

In [37]:
ae2 = np.expand_dims(a,axis=0)
ae2.shape

(1, 5)

## Soal

In [58]:
arr = np.array([[1,20,7,4,10],[1,2,3,4,5],[9,3,4,5,6]])
print(arr[arr>=3])

[20  7  4 10  3  4  5  9  3  4  5  6]


In [60]:
a_1 = np.array([[1,1],[2,2]])

a_2 = np.array([[3,3],[4,4]])

np.vstack([a_1, a_2])

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [61]:
a_1 = np.array([[1,1],[2,2]])

a_2 = np.array([[3,3],[4,4]])

np.hstack([a_1, a_2])

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [64]:
arr_new = np.array([[1,2,3,4,5,6,7,8,9,10,11,12]])
new_arr = arr_new.reshape(2,3,-1)
print(new_arr)
print(new_arr.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)


In [69]:
arr_new.std()

3.452052529534663